# Generated by Django 3.2.9 on 2021-12-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lopa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cause',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='cause_barrier',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='consequence',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='consequence_barrier',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='modified_at',
            new_name='updated_at',
        ),
    ]
