# Generated by Django 3.2.9 on 2021-12-03 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lopa', '0002_auto_20211202_1545'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UUIDModel',
        ),
        migrations.RenameField(
            model_name='consequence_barrier',
            old_name='cause',
            new_name='consequence',
        ),
    ]
